project_id = "sjopaiquzqotymqmrcke"
[functions.register-node]
verify_jwt = false

[functions.sync-models-cron]
verify_jwt = false

[functions.node-heartbeat]
verify_jwt = false

[functions.ingest-usage-stats]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
